### ISSUE TITLE
Intel Movidius Neural Compute Stick 2 

### ISSUE THREAD

**Issue by MoonUniverse** [mpkuse/tx2_whole_image_desc_server#1]
hi,mpkuse!
      Recently,i want to deploy trained models on neural compute stick 2.I got some problems during this process,i can't convert the model from PB to IR.I think the reason should be that openvino cannot convert custom layers( NetVLADLayer).I have no idea at the moment,can you give me some advice.
      Thank you very much!

**Comment by mpkuse** [comment]
yes I have also encounter issue with converting NetVLAD layer. Someone in our lab was trying to do just the CNN computation on GPU and do NetVLAD computation using numpy on CPU (work in progress). Maybe you could try it as well. If you have any luck running this on compute stick, do share with us.

**Comment by MoonUniverse** [comment]
Thank you for your reply!
